[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "ibfleming"
name = "Fimbulwinter"
description = "A veteran's Valheim modpack: tuned for challenging multiplayer with deeper combat, loot, creatures, magic, and QoL."
versionNumber = "1.3.1"
websiteUrl = "https://github.com/ibfleming/fimbulwinter"

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2333"
ValheimModding-Jotunn = "2.27.1"
ValheimModding-JsonDotNET = "13.0.4"
ValheimModding-YamlDotNet = "16.3.1"
MSchmoecker-StartupHotfix = "0.1.0"
shudnal-ConfigurationManager = "1.1.12"
JereKuusela-Server_devcommands = "1.102.0"
zamboni-Gungnir = "1.7.6"
Smoothbrain-CreatureLevelAndLootControl = "4.6.4"
RandyKnapp-EpicLoot = "0.12.10"
JewelHeim-EpicLoot_Therzie = "2.1.1"
Therzie-Warfare = "1.8.9"
Therzie-WarfareFireAndIce = "2.0.8"
Therzie-Armory = "1.3.1"
Therzie-Monstrum = "1.5.1"
Therzie-MonstrumDeepNorth = "2.0.6"
Therzie-Wizardry = "1.1.8"
ASharpPen-Custom_Raids = "1.8.1"
ASharpPen-This_Goes_Here = "2.1.2"
ASharpPen-Drop_That = "3.1.3"
ASharpPen-Spawn_That = "1.2.18"
Soloredis-RtDOcean = "1.5.2"
Soloredis-RtDDungeons = "0.4.3"
Soloredis-RtDHorrors = "0.4.9"
Soloredis-RtDMonsters = "2.2.8"
Soloredis-RtDMonstrum = "0.8.1"
warpalicious-Forbidden_Catacombs = "1.0.2"
warpalicious-More_World_Locations_AIO = "4.1.1"
Marlthon-OdinShip = "0.7.4"
HappyDragoon-DragoonCapes = "1.3.5"
OdinPlus-OdinHorse = "1.5.8"
blacks7ar-CookingAdditions = "1.3.1"
Revel-Headshots = "1.0.2"
ishid4-BetterArchery = "1.9.82"
Korppis-ReliableBlock = "1.0.0"
blacks7ar-Agility = "1.1.7"
blacks7ar-Endurance = "1.1.1"
Searica-SkilledCarryWeight = "1.4.1"
Smoothbrain-SmartSkills = "1.0.2"
Smoothbrain-Tenacity = "1.0.4"
BetterUI_ForeverMaintained-BetterUI_ForeverMaintained = "2.5.9"
RustyMods-Seasonality = "3.7.9"
Willybach-Willybachs_HD_Seasonality = "3.5.6"
Neobotics-HUDCompass = "1.1.7"
shudnal-GammaOfNightLights = "1.0.8"
Vapok-AdventureBackpacks = "1.9.10"
Azumatt-AzuExtendedPlayerInventory = "2.3.4"
Azumatt-AzuCraftyBoxes = "1.8.13"
Azumatt-AzuAutoStore = "3.0.11"
Azumatt-AzuContainerSizes = "1.1.4"
Azumatt-AAA_Crafting = "2.1.6"
Azumatt-Recycle_N_Reclaim = "1.3.10"
Azumatt-AzuHoverStats = "1.1.9"
Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock = "1.4.13"
Smoothbrain-Groups = "1.2.10"
Azumatt-PetPantry = "1.0.5"
Azumatt-SaveCrossbowState = "1.0.2"
blacks7ar-LazyVikings = "1.2.3"
Digitalroot-Eternal_Fire = "1.0.17"
Nextek-SpeedyPaths = "1.0.9"
RandomSteve-BreatheEasy = "1.0.5"
coemt-StumpsAreOneHp = "0.0.1"
Searica-CameraTweaks = "1.3.1"
OdinPlus-TeleportEverything = "2.9.1"
Searica-AdvancedTerrainModifiers = "1.4.1"
BentoG-MissingPieces = "2.2.2"
JoelOliMclean-NoRainDamage = "1.2.4"
Advize-PlantEverything = "1.20.0"
Advize-PlantEasily = "2.0.3"
Smoothbrain-Sailing = "1.1.8"
Smoothbrain-SailingSpeed = "1.0.3"
Marlthon-SeaAnimals = "0.3.4"
Horem-Fee_Fi_Fo_Fum = "0.1.9"
Huntardys-EpicValheimsAdditions = "2.1.2"
Azumatt-TrueInstantLootDrop = "1.0.3"
shudnal-TradersExtended = "1.3.12"
JereKuusela-Structure_Tweaks = "1.35.0"
Azumatt-MyPitsDontLeak = "1.0.0"
blacks7ar-WieldEquipmentWhileSwimming = "1.1.3"
coemt-Birds = "0.2.0"
Horem-MushroomMonsters = "1.0.2"
CacoFFF-LeanNet = "1.0.1"
ComfyMods-Scenic = "1.5.0"
MSchmoecker-MultiUserChest = "0.6.1"
MSchmoecker-TimeoutLimit = "0.2.0"
MSchmoecker-LocalizationCache = "0.3.0"
OdinPlus-BeeQueen = "1.1.0"
Searica-NetworkTweaks = "0.1.5"
Smoothbrain-ShutUp = "1.0.2"
Smoothbrain-Mining = "1.1.6"
Smoothbrain-Resurrection = "1.0.13"
Smoothbrain-ServerCharacters = "1.4.16"
Smoothbrain-Foraging = "1.0.10"
Smoothbrain-Farming = "2.2.2"
Radamanto-Bestiary = "1.1.4"
Smoothbrain-DualWield = "1.0.10"
Smoothbrain-Evasion = "1.0.4"
Smoothbrain-Lumberjacking = "1.0.6"
Smoothbrain-Building = "1.2.6"
Smoothbrain-Blacksmithing = "1.3.3"
Searica-ProjectileTweaks = "1.6.0"
shudnal-CircletExtended = "1.1.9"
Mexanik-ShieldBash = "1.5.1"
nbusseneau-Better_Cartography_Table = "0.8.1"

[publish]
communities = ["valheim"]

[publish.categories]
valheim = ["modpacks", "server-side", "enemies", "gear", "tweaks"]

[build]

[[build.copy]]
source = "config"
target = "config"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"
